name: Hello, World!
description: Greet someone and record the time
author: GitHub Actions

# Define your inputs here.
inputs:
  github-token:
    description: GitHub token
    required: true
  jira-base-url:
    description: Organization base url
    required: true
  jira-api-key:
    description: Jira api key
    required: true
  jira-user-email:
    description: Jira user email used as part of the credentials
    required: true
  fail-when-jira-issue-not-found:
    description: Fail the workflow when the Jira issue is not found
    required: false
    default: false

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
