name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      jira-token:
        description: Who to greet in the log
        required: true
        type: string
      jira-base-url:
        description: The base URL for the Jira instance
        required: true
        type: string
      fail-when-jira-issue-not-found:
        description: Fail the workflow when the Jira issue is not found
        required: false
        type: boolean

permissions:
  actions: read
  contents: read

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      # Change @main to a specific commit SHA or version tag, e.g.:
      # actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
      # actions/hello-world-javascript-action@v1.2.3
      - name: Print to Log
        id: print-to-log
        uses: reachtrevor/jira-enrich-pr-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ inputs.jira-token }}
          jira-base-url: ${{ inputs.jira-base-url }}
          fail-when-jira-issue-not-found: |
            ${{ inputs.fail-when-jira-issue-not-found }}
