name: Example PR Workflow

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  actions: write
  contents: write

jobs:
  enrich-pr-with-jira:
    name: Enrich PR with Jira
    runs-on: ubuntu-latest

    steps:
      # Change @main to a specific commit SHA or version tag, e.g.:
      # actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
      # actions/hello-world-javascript-action@v1.2.3
      - name: Print to Log
        id: print-to-log
        uses: reachtrevor/jira-enrich-pr-action@GN-25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_API_KEY }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
